WITH SUBQUERY1 AS (
SELECT DISTINCT DAM_CONTACTABILIDAD.IDMOROSO, IDCLIENTE,ESTADO,FILTROA
FROM Active.dbo.DAM_CONTACTABILIDAD
LEFT JOIN Active.dbo.Cartera
ON Active.dbo.Cartera.IDMOROSO = Active.dbo.DAM_CONTACTABILIDAD.IDMOROSO
WHERE PROVEEDOR_DATO = 'AD'
AND IDCLIENTE = 'FRANCES_2012'
AND FECHA_INGRESO_DATO BETWEEN '19/03/2021' AND '20/03/2021'),
SUBQUERY2 AS(
SELECT IDMOROSO, SCORING_MOPC
FROM ACTIVE.dbo.DAM_DATOS_PERSONALES)
SELECT SUBQUERY1.IDMOROSO, SUBQUERY1.IDCLIENTE,SUBQUERY1.ESTADO,SUBQUERY1.FILTROA, SUBQUERY2.SCORING_MOPC
FROM SUBQUERY1
LEFT JOIN SUBQUERY2
ON SUBQUERY1.IDMOROSO = SUBQUERY2.IDMOROSO