WITH SUBQUERY1 AS (
SELECT ACTIVE.dbo.DAM_CONTACTABILIDAD.IDMOROSO, DATO, ACTIVE.dbo.CARTERA.IDCLIENTE,ACTIVE.dbo.CARTERA.ESTADO, ACTIVE.dbo.CARTERA.FILTROA
FROM ACTIVE.dbo.DAM_CONTACTABILIDAD
LEFT JOIN ACTIVE.dbo.CARTERA ON ACTIVE.dbo.CARTERA.IDMOROSO = ACTIVE.dbo.DAM_CONTACTABILIDAD.IDMOROSO
WHERE ACTIVE.dbo.DAM_CONTACTABILIDAD.PROVEEDOR_DATO = 'AD'
AND FECHA_INGRESO_DATO BETWEEN '19/03/2021' AND '20/03/2021'
AND ESTADO <> 'DEVUELTO'
AND IDCLIENTE = 'FRANCES_2012'
)
, SUBQUERY2 AS (
SELECT IDMOROSO, DATO, COUNT (*) AS CANTIDAD_APARICIONES FROM ACTIVE.dbo.DAM_CONTACTABILIDAD
GROUP BY IDMOROSO, DATO)
SELECT SUBQUERY1.IDMOROSO, SUBQUERY1.DATO, SUBQUERY1.IDCLIENTE, SUBQUERY1.ESTADO, SUBQUERY1.FILTROA FROM SUBQUERY1
INNER JOIN SUBQUERY2
ON SUBQUERY1.IDMOROSO = SUBQUERY2.IDMOROSO
AND SUBQUERY1.DATO = SUBQUERY2.DATO
AND CANTIDAD_APARICIONES = 1
ORDER BY IDCLIENTE, FILTROA, IDMOROSO