
-----------UPDATE------------------
UPDATE ACTIVE.dbo.DAM_DATOS_PERSONALES
SET [SCORING_MOPC] = (
select [SCORING_MOPC] 
from AT.DBO.DAM_DATOS_PERSONALES_TEMP 
where DAM_DATOS_PERSONALES.IDMOROSO = AT.DBO.DAM_DATOS_PERSONALES_TEMP.idmoroso)
WHERE EXISTS (
SELECT * 
FROM AT.DBO.DAM_DATOS_PERSONALES_TEMP 
WHERE DAM_DATOS_PERSONALES.IDMOROSO = AT.DBO.DAM_DATOS_PERSONALES_TEMP.idmoroso ) 

--SELECT *
--FROM DAM_DATOS_PERSONALES
--WHERE not EXISTS (SELECT * FROM AT.DBO.DAM_DATOS_PERSONALES_TEMP WHERE DAM_DATOS_PERSONALES.IDMOROSO = AT.DBO.DAM_DATOS_PERSONALES_TEMP.idmoroso )

----------------INSERT---------------------
insert into DAM_DATOS_PERSONALES
SELECT [IDMOROSO]
      ,[NOMBRE_COMPLETO]
      ,[GENERO]
      ,[FECHA_NACIMIENTO]
      ,[ESTADO_CIVIL]
      ,[HIJOS]
      ,[SCORING_MOPC]
      ,[SCORING_FINANCIERO]
      ,[SCORING_TERCEROS]
      ,[NIVEL_DE_INGRESO]
      ,[FECHA_ULTIMO_PAGO]
  FROM AT.DBO.DAM_DATOS_PERSONALES_TEMP
  WHERE not EXISTS (
  SELECT DAM_DATOS_PERSONALES.IDMOROSO 
  FROM DAM_DATOS_PERSONALES 
  WHERE DAM_DATOS_PERSONALES.IDMOROSO = AT.DBO.DAM_DATOS_PERSONALES_TEMP.idmoroso ) 