SELECT MOROSO.IDMOROSO, NOMBRE, TELPART AS DATO, 'TELEFONO' AS TIPO, IDCLIENTE, DATOADIC, TELPARTS AS VERIFICADO, 'AT' AS PROVEEDOR_DATO FROM Active.dbo.MOROSO
LEFT JOIN Active.dbo.CARTERA
ON Active.dbo.Cartera.IDMOROSO = Active.dbo.MOROSO.IDMOROSO
WHERE TELPART IS NOT NULL AND TELPART <> '' AND TELPART <> '0' 
UNION ALL
SELECT MOROSO.IDMOROSO, NOMBRE, TELCEL AS DATO, 'TELEFONO' AS TIPO, IDCLIENTE, DATOADIC, TELCELS AS VERIFICADO, 'AT' AS PROVEEDOR_DATO FROM Active.dbo.MOROSO
LEFT JOIN Active.dbo.CARTERA
ON Active.dbo.Cartera.IDMOROSO = Active.dbo.MOROSO.IDMOROSO
WHERE TELCEL IS NOT NULL AND TELCEL <> '' AND TELCEL <> '0'
UNION ALL
SELECT MOROSO.IDMOROSO, NOMBRE, TELALT1 AS DATO, 'TELEFONO' AS TIPO, IDCLIENTE, DATOADIC, TELALT1S AS VERIFICADO, 'AT' AS PROVEEDOR_DATO  FROM Active.dbo.MOROSO
LEFT JOIN Active.dbo.CARTERA
ON Active.dbo.Cartera.IDMOROSO = Active.dbo.MOROSO.IDMOROSO
WHERE TELALT1 IS NOT NULL AND TELALT1 <> '' AND TELALT1 <> '0'
UNION ALL
SELECT MOROSO.IDMOROSO, NOMBRE, TELALT2 AS DATO, 'TELEFONO' AS TIPO, IDCLIENTE, DATOADIC, TELALT2S AS VERIFICADO, 'AT' AS PROVEEDOR_DATO  FROM Active.dbo.MOROSO
LEFT JOIN Active.dbo.CARTERA
ON Active.dbo.Cartera.IDMOROSO = Active.dbo.MOROSO.IDMOROSO
WHERE TELALT2 IS NOT NULL AND TELALT2 <> '' AND  TELALT2 <> '0'
UNION ALL
SELECT MOROSO.IDMOROSO, NOMBRE, EMAIL1 AS DATO, 'MAIL' AS TIPO, IDCLIENTE, DATOADIC, NULL AS VERIFICADO, 'AT' AS PROVEEDOR_DATO  FROM Active.dbo.MOROSO
LEFT JOIN Active.dbo.CARTERA
ON Active.dbo.Cartera.IDMOROSO = Active.dbo.MOROSO.IDMOROSO
WHERE EMAIL1 IS NOT NULL AND EMAIL1 <> '' AND EMAIL1 <> '0'