SELECT c.IDMOROSO, m.NOMBRE, c.IDCLIENTE, c.ESTADO,
c.FILTROA, m.DATOADIC, c.FASIGNACION
FROM Active.dbo.CARTERA c
LEFT JOIN Active.dbo.MOROSO m
ON c.IDMOROSO = m.IDMOROSO
WHERE c.FASIGNACION >= CAST('2021-01-01' AS DATE)
AND c.ESTADO NOT IN ('DEVUELTO')
AND IDCLIENTE IN ('FRANCES_2012', 'BSR_TARDIA', 'AMEX_ALHR','AMEX_ALLR','AMEX_PALM','AMEX_PARM',
	'AMEX_PBLM', 'AMEX_PBRM','AMEX_PELM','AMEX_PFLM','AMEX_PNCM','AMEX_QRNM','AMEX_QRPM','AMEX_TNCM',
	'AMEX_TNLM','AMEX_TNRM', 'HSBC_LEGALES14', 'HSBC_LEGALES_TEMP', 'BBVA_LEGALES_PREJU',
	'BBVA_LEGALES_PREJU_5', 'HSBC_FOGAR','PRENDARIOS_LEGALES','BBVA_LEGALES_PREJU_EMP','COTO_TARDIA')
